load(":semver_tests.bzl", "semver_test_suite")
load(":queue_tests.bzl", "queue_test_suite")
load(":fetcher_tests.bzl", "fetcher_test_suite")
load(":solver_tests.bzl", "solver_test_suite")

semver_test_suite()

queue_test_suite()

fetcher_test_suite()

solver_test_suite()
